### ISSUE TITLE
Link returns 404

### ISSUE THREAD

**Issue by Aakash1103Jha** [Bharvi-Sampat/Portfolio-Demo-SASS#1]
This link - `https://bharvi-sampat.github.io/Portfolio-Demo-SASS/` - returns `404`. Is there something I missed, a subpath, or a page name that should be followed after `...SASS/`

**Comment by Aakash1103Jha** [comment]
I had to add `/dist/index.html` to get to the right place.

**Comment by Bharvi-Sampat** [comment]
Yes I was just gonna get back to you

Thats correct you uad to add /dist/css to the sass path
